version: '3'

services:

  nginx:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - USE_SSL=0
      - DH_SIZE=2048
      - ERROR_LOG_LEVEL=warn
      - SERVER_NAME=app
      - FASTCGI_PASS_HOST=127.0.0.1:9000