version: '3'

services:

  nginx:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - USE_HTTP=1
      - USE_HTTPS=0
      - SSL_CLOUDFLARE_EMAIL=
      - SSL_CLOUDFLARE_API_KEY=
      - SSL_CLOUDFLARE_TOKEN=
      - SSL_EMAIL=
      - SSL_DOMAIN=
      - DH_SIZE=2048
      - NGINX_ERROR_LOG_LEVEL=warn
      - NGINX_BASE_PATH=/app
      - SERVER_NAME=app
      - FASTCGI_PASS_HOST=php:9000